---
title: "Anand Rath"
about:
  template: jolla
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
---

[Brief bio text highlighting experience in industrial analytics, machine learning, and interests in geopolitics and quantum computing.]

## Education

**MTech. in Computer Science**, IIIT | Bangalore

**BTech. in Computer Science**, BPUT | Odisha

## Experience

2026 - present: **Pingala | Numerics**&#8482, CEO

2019 - 2025: **Industrial Analytics Industry**, Research Consultant

2011 - 2019: **ABB**, Scientist, Corporate Research

2009 - 2011: **ABB**, Research Intern 2009 - 2011

## Publications

  * [Military Digital Twins - a Data-Hardened Architecture for Digital Twins to Enable Operational Resilience in Adversarial Environments, ICADS 2026: 1-6](https://ieeexplore.ieee.org/document/11545475)
  
  * [Dachi: A networked querying system for industrial Internet of Things applications. ETFA 2017: 1-4](https://ieeexplore.ieee.org/document/8247716)


  * [Analyzing Dependencies in an Industrial Automation Engineering System. ISEC 2015: 60-69](https://dl.acm.org/doi/10.1145/2723742.2723748)


  * [An approach for comparison of IEC 61131-3 graphical programs. ETFA 2013: 1-8](https://ieeexplore.ieee.org/document/6647938)


  * [Field weighting for automatic bug triaging systems. SMC 2012: 2845-2848](https://ieeexplore.ieee.org/document/6378180)

## Patents

  * A method for managing subsystems of a process plant using a distributed control system | WO2016059484A1 WIPO (PCT)


  * Condition monitoring of wireless networks in industrial plants | US10931551B2 United States


  * A method and device for communicating process information in wireless network of industrial plant | WO2020240004A1 WIPO (PCT)
